### ISSUE TITLE
What‘s the difference between 'Research' mode and 'Standard' mode?

### ISSUE THREAD

**Issue by lidh15** [CymatiCorp/CyKITv2#15]
How can I see which mode I should use for my device?

**Comment by warrenarea** [comment]
I think a few of Emotiv products will tell you what the current mode is.

My next version of CyKIT will have the support to let you view what the current mode is,
and will let you change it.

You should be able to change it currently, by plugging your device into the USB, and then 
running CyKITv2.py

**Comment by lidh15** [comment]
I'm using 'Standard' mode now. 
One thing I found necessary is that when using EmotivPro I can see clearly the connection quality of the electrodes (green, orange, red or null) so that I can adjust them properly. Would you please add this module in CyKIT?

**Comment by warrenarea** [comment]
that is a feature i added, and will be available in the next release.

**Comment by lidh15** [comment]
Thanks a lot.
