### ISSUE TITLE
how to save data

### ISSUE THREAD

**Issue by wangwuqi** [CymatiCorp/CyKITv2#3]
really great work, I've got it run on my computer with epoch+, what i really need is the data, since you can plot all the channels, it must be easy to add a function for users to save data.
<img width="761" alt="default" src="https://user-images.githubusercontent.com/22237278/32707138-c8c84d36-c85c-11e7-87b0-0ea38ff798bc.PNG">

**Comment by warrenarea** [comment]
that image doesn't look correctly.... the baseline needs to be reset...
look into the cyinterace.js and see if you can't find my reset_Baseline function... 
that way the data is plotted in the "middle" of the screen.

i haven't gotten too far into the "saving data" aspect... especially because, the data isn't
really accurate at this point.... the data for Insight/Epoc+ need their own version of Get_Level
and i haven't sorted that out yet.

**Comment by warrenarea** [comment]
I updated the Epoc so it displays correctly.
You could try changing your Epoc+ to Epoc-mode. 

You can do that in Xavier control panel... i do have the code to change it in python,
but haven't set it up yet.

**Comment by wangwuqi** [comment]
In Xavier control panel, there're two mode to select, Epoc and Insight. My headset is epoc+.
![image](https://user-images.githubusercontent.com/22237278/33000461-2ceb9896-cde3-11e7-9e80-39d1f0d61655.png)

**Comment by warrenarea** [comment]
i think that is to be expected. 

i also fixed a couple of mistakes in my CyKITv2 version, 
which fixed the battery levels not being reported correctly as well as a slight data problem.

it still isn't properly set up entirely though. still working on it.

Emotiv Xavier control panel as far as i know, only will show "Epoc" or "Insight" mode.

They do have a new product now i think they're focusing on now, called EmotivPRO,
which they have improved their rendering of the data.

**Comment by warrenarea** [comment]
https://discord.gg/gTYNWc7
If anyone would like to assist me in the Epoc+ data
I have a Discord chat server setup here.  

You can either download the discord chat messenger, 
or just click the link to use the browser interface.

**Comment by warrenarea** [comment]
https://discord.gg/gTYNWc7
If anyone would like to assist me in the Epoc+ data
I have a Discord chat server setup here.

You can either download the discord chat messenger,
or just click the link to use the browser interface.

**Comment by warrenarea** [comment]
New version update.
