### ISSUE TITLE
CyKITv2 seem not to react properly with my EPOC+

### ISSUE THREAD

**Issue by xdhuanglipeng** [CymatiCorp/CyKITv2#5]
`python CyKITv2.py 127.0.0.1 55555 6 info`
`> Listening on 127.0.0.1 : 55555`
`> Trying Key Model #: 6`
`* Connecting . . .`
`> Connected!`
`<socket._socketobject object at 0x01E7B148>`
`MainThread`
`Product name Brain Computer Interface USB Receiver/Dongle`
`device path \\?\hid#vid_1234&pid_ed02&mi_00#8&652ddc4&0&0000#{4d1e55b2-f16f-11cf
-88cb-001111000030}`
`instance id HID\VID_1234&PID_ED02&MI_00\8&652DDC4&0&0000`
`________________________________________________________________________________`

`>>> Found EEG Device >>> Brain Computer Interface USB Receiver/Dongle`

`> Using Device: Brain Computer Interface USB Receiver/Dongle`

`  Serial Number: UD20160303001D0F`
`Product name EEG Signals`
`device path \\?\hid#vid_1234&pid_ed02&mi_01#8&2a2a1b86&0&0000#{4d1e55b2-f16f-11c
f-88cb-001111000030}`
`instance id HID\VID_1234&PID_ED02&MI_01\8&2A2A1B86&0&0000`
`________________________________________________________________________________`

`>>> Found EEG Device >>> EEG Signals`

`> Using Device: EEG Signals`

`  Serial Number: UD20160303001D0F`

`Thread-1`
`ioThread`
`Thread-3`
`MainThread`
`Thread-2`
`eegThread`
`Thread-4`

`Active Threads = {`
`   <InputReportProcessingThread ::: Thread-1>`
`   <Thread ::: ioThread>`
`   <InputReportProcessingThread ::: Thread-3>`
`   <_MainThread ::: MainThread>`
`   <InputReportReaderThread ::: Thread-2>`
`   <Thread ::: eegThread>`
`   <InputReportReaderThread ::: Thread-4>`
`}`

Then , the console doesn't print any more, and website can't see any eeg lines. what's the problem?

**Comment by warrenarea** [comment]
A new version has been updated, i recommend upgrading.
