### ISSUE TITLE
py 3+

### ISSUE THREAD

**Issue by mehransahandi** [CymatiCorp/CyKITv2#6]
thanks for this useful code
some questions?
dose it work with epoc+ 2017+ models ?
does it work with py3+?

**Comment by warrenarea** [comment]
works with all models, Epoc, Insight, Epoc+
does not support py3. only 2.7.6

**Comment by tafaust** [comment]
Actually, I am working to port to python 3.+ while simultaneously porting to linux… thought it takes more time and usually won't be as up-to-date as this repository.
––
I'll continue work on the fork as soon as I get back from my vacation! (I also have some issues with my device which stop me from testing…)

**Comment by warrenarea** [comment]
https://github.com/tahesse/CyKITv2
